In [1]:
import pandas as pd
import numpy as np

# Heavy Metals Data

In [2]:
df_metals = pd.read_excel('C:/Users/Administrador/OneDrive/Ambiente de Trabalho/Article_Organize_Data/combined_df.xlsx')
df_metals

No Amostra Data de colheita Zona de_x000D_Produção  \
0        353/21       12/04/2021                    L5a   
1        362/21       13/04/2021                   ETJ1   
2        363/21       13/04/2021                   ESD1   
3        366/21       13/04/2021                RIAV NZ   
4        369/21       19/04/2021                    LOB   
...         ...              ...                    ...   
2156    1046/22       28/09/2022                  RIAV1   
2157    1047/22       28/09/2022                     L1   
2158    1048/22       28/09/2022                     L1   
2159    1049/22       28/09/2022                     L1   
2160    1051/22       28/09/2022                   ESD2   

                               Local           Espécie Cd\n(mg/kg)  \
0                    Praia dos Coxos              Lapa         2.3   
1                           Cacilhas       Pé-de-burro        0.24   
2                      Canal da Vaia  Ostra-portuguesa         0.5   
3                   Bolho da Malhada     Ostra-gigante        0.18   
4                            Greijau   Amêijoa-relógio        0.09   
...                              ...               ...         ...   
2156  Frente Colónia Férias Torreira  Amêijoa-japonesa        0.26   
2157                         Carreço          Mexilhão        0.28   
2158                         Carreço              Lapa         0.8   
2159                         Carreço     Ouriço-do-mar        0.14   
2160                    Carrasqueira        Longueirão        0.07   

     Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
0          0.013             0.10   
1          0.028             0.24   
2          0.026             0.12   
3          0.045             0.14   
4          0.011              0.7   
...          ...              ...   
2156       0.017             0.06   
2157       0.012             0.18   
2158     < 0.011             0.37   
2159     < 0.011           < 0.06   
2160       0.020             0.11   

      Resultados das Determinações de Metais Contaminantes  \
0                                                   NaN      
1                                                   NaN      
2                                                   NaN      
3                                                   NaN      
4                                                   NaN      
...                                                 ...      
2156                                                NaN      
2157                                                NaN      
2158                                                NaN      
2159                                                NaN      
2160                                                NaN      

      Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
0                        NaN  ...         NaN   NaN              NaN    NaN   
1                        NaN  ...         NaN   NaN              NaN    NaN   
2                        NaN  ...         NaN   NaN              NaN    NaN   
3                        NaN  ...         NaN   NaN              NaN    NaN   
4                        NaN  ...         NaN   NaN              NaN    NaN   
...                      ...  ...         ...   ...              ...    ...   
2156                     NaN  ...         NaN   NaN              NaN    NaN   
2157                     NaN  ...         NaN   NaN              NaN    NaN   
2158                     NaN  ...         NaN   NaN              NaN    NaN   
2159                     NaN  ...         NaN   NaN              NaN    NaN   
2160                     NaN  ...         NaN   NaN              NaN    NaN   

      Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
0                      NaN          NaN    NaN    NaN   NaN        NaN  
1                      NaN          NaN    NaN    NaN   NaN        NaN  
2                      NaN          NaN    NaN    NaN   NaN        NaN  
3                      N

__Missing Values__

In [3]:
df_metals.isnull().sum() / df_metals.shape[0] * 100

No Amostra                                                                                                                                   0.000000
Data de colheita                                                                                                                             0.000000
Zona de_x000D_Produção                                                                                                                       0.000000
Local                                                                                                                                        0.000000
Espécie                                                                                                                                      0.046275
Cd\n(mg/kg)                                                                                                                                  0.509024
Hg\n(mg/kg)                                                                                         

_Espécie_

In [4]:
df_metals[df_metals['Espécie'].isnull()]

No Amostra Data de colheita Zona de_x000D_Produção    Local Espécie  \
641      15649       26-07-2016                   ESD1  Setúbal     NaN   

    Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
641        0,34         NaN             0,16   

     Resultados das Determinações de Metais Contaminantes  \
641                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
641                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
641                   NaN          NaN    NaN    NaN   NaN        NaN  

[1 rows x 56 columns]

In [5]:
# Fill missing values in the 'Espécie' column with 'Ostra-portuguesa'
df_metals.loc[df_metals['Espécie'].isnull(), 'Espécie'] = 'Ostra-portuguesa'

_Cd_x000D_(mg/kg)

In [6]:
df_metals[df_metals['Cd\n(mg/kg)'].isnull()]

No Amostra Data de colheita    Zona de_x000D_Produção  \
366       14061         9/7/2015  ESD1 Esteiro da Marateca   
367       14095        16/7/2015     ESD2 Canal de Alcácer   
368       14116        22/7/2015  ESD1 Esteiro da Marateca   
369       14118        13/8/2015     ESD2 Canal de Alcácer   
370       14199        17/8/2015                       EMR   
1894      19587        19/9/2019                       LOB   
1895      19588        19/9/2019                       LOB   
1896      19592        24/9/2019                       LOB   
1897      19593        24/9/2019                       LOB   
1898      19594        24/9/2019                       LOB   
1899      19595        24/9/2019                       LOB   

                     Local               Espécie Cd\n(mg/kg) Hg\n(mg/kg)  \
366                 Gambia  Crassostrea angulata         NaN       0.018   
367    Casas Novas/Batalha  Crassostrea angulata         NaN       0.053   
368          Canal da Vaia  Crassostrea angulata         NaN       0.014   
369       Motante da Ponte  Crassostrea angulata         NaN        0.02   
370     Roncão/Casa Branca  Crassostrea angulata         NaN       0.021   
1894  Frente à Escola Vela              Mexilhão         NaN         NaN   
1895              Espichel              Berbigão         NaN         NaN   
1896               Greijau         Amêijoa-macha         NaN         NaN   
1897              Espichel           Amêijoa-boa         NaN         NaN   
1898              Espichel      Amêijoa-japonesa         NaN         NaN   
1899              Espichel            Longueirão         NaN         NaN   

     Pb_x000D_(mg/kg)  Resultados das Determinações de Metais Contaminantes  \
366               0.1                                                NaN      
367              0.13                                                NaN      
368              0.13                                                NaN      
369              0.24                                                NaN      
370              0.14                                                NaN      
1894             0,60                                                NaN      
1895             0,16                                                NaN      
1896           < 0,06                                                NaN      
1897             0,07                                                NaN      
1898             0,06                                                NaN      
1899             0,09                                                NaN      

      Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
366                      NaN  ...         NaN   NaN              NaN    NaN   
367                      NaN  ...         NaN   NaN              NaN    NaN   
368                      NaN  ...         NaN   NaN              NaN    NaN   
369                      NaN  ...         NaN   NaN              NaN    NaN   
370                      NaN  ...         NaN   NaN              NaN    NaN   
1894                     NaN  ...         NaN   NaN              NaN    NaN   
1895                     NaN  ...         NaN   NaN              NaN    NaN   
1896                     NaN  ...         NaN   NaN              NaN    NaN   
1897                     NaN  ...         NaN   NaN              NaN    NaN   
1898                     NaN  ...         NaN   NaN              NaN    NaN   
1899                     NaN  ...         NaN   NaN              NaN    NaN   

      Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
366                    NaN          NaN    NaN    NaN   NaN        NaN  
367                    NaN          NaN    NaN    NaN   NaN        NaN  
368                    NaN          NaN    NaN    NaN   NaN        NaN  
369                    NaN          NaN    NaN    NaN   NaN        NaN  
370                    NaN          NaN    NaN    NaN   NaN        NaN  
1894       

In [7]:
# No Amostra = 14061
df_metals[df_metals['No Amostra']==14061]

No Amostra Data de colheita    Zona de_x000D_Produção   Local  \
366      14061         9/7/2015  ESD1 Esteiro da Marateca  Gambia   
639      14061         7/9/2015  ESD1 Esteiro da Marateca  Gambia   

                  Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
366  Crassostrea angulata         NaN       0.018              0.1   
639      Ostra-portuguesa        0.39       0.018              0.1   

     Resultados das Determinações de Metais Contaminantes  \
366                                                NaN      
639                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
366                     NaN  ...         NaN   NaN              NaN    NaN   
639                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
366                   NaN          NaN    NaN    NaN   NaN        NaN  
639                   NaN          NaN    NaN    NaN   NaN        NaN  

[2 rows x 56 columns]

In [8]:
# Drop index=366
df_metals = df_metals.drop(index=366)

In [9]:
# No Amostra = 14095
df_metals[df_metals['No Amostra']==14095]

No Amostra Data de colheita Zona de_x000D_Produção                Local  \
367      14095        16/7/2015  ESD2 Canal de Alcácer  Casas Novas/Batalha   

                  Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
367  Crassostrea angulata         NaN       0.053             0.13   

     Resultados das Determinações de Metais Contaminantes  \
367                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
367                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
367                   NaN          NaN    NaN    NaN   NaN        NaN  

[1 rows x 56 columns]

In [10]:
# Replace missing values in the 'Cd_x000D_(mg/kg)' column where 'No Amostra' is 14095 with '1,9'
df_metals.loc[df_metals['No Amostra'] == 14095, 'Cd\n(mg/kg)'] = 1.9

In [11]:
# No Amostra = 14116
df_metals[df_metals['No Amostra']==14116]

No Amostra Data de colheita    Zona de_x000D_Produção          Local  \
368      14116        22/7/2015  ESD1 Esteiro da Marateca  Canal da Vaia   
640      14116        7/22/2015  ESD1 Esteiro da Marateca  Canal da Vaia   

                  Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
368  Crassostrea angulata         NaN       0.014             0.13   
640      Ostra-portuguesa         0.6       0.014             0.13   

     Resultados das Determinações de Metais Contaminantes  \
368                                                NaN      
640                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
368                     NaN  ...         NaN   NaN              NaN    NaN   
640                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
368                   NaN          NaN    NaN    NaN   NaN        NaN  
640                   NaN          NaN    NaN    NaN   NaN        NaN  

[2 rows x 56 columns]

In [12]:
# Drop index = 368
df_metals = df_metals.drop(index=368)

In [13]:
# No Amostra = 14118
df_metals[df_metals['No Amostra']==14118]

No Amostra Data de colheita Zona de_x000D_Produção             Local  \
369      14118        13/8/2015  ESD2 Canal de Alcácer  Motante da Ponte   

                  Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
369  Crassostrea angulata         NaN        0.02             0.24   

     Resultados das Determinações de Metais Contaminantes  \
369                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
369                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
369                   NaN          NaN    NaN    NaN   NaN        NaN  

[1 rows x 56 columns]

In [14]:
# Replace missing values in the 'Cd_x000D_(mg/kg)' column where 'No Amostra' is 14118 with '1,9'
df_metals.loc[df_metals['No Amostra'] == 14118, 'Cd\n(mg/kg)'] = 1.4

In [15]:
# No Amostra = 14199
df_metals[df_metals['No Amostra']==14199]

No Amostra Data de colheita Zona de_x000D_Produção               Local  \
370      14199        17/8/2015                    EMR  Roncão/Casa Branca   

                  Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
370  Crassostrea angulata         NaN       0.021             0.14   

     Resultados das Determinações de Metais Contaminantes  \
370                                                NaN      

     Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
370                     NaN  ...         NaN   NaN              NaN    NaN   

     Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
370                   NaN          NaN    NaN    NaN   NaN        NaN  

[1 rows x 56 columns]

In [16]:
# Replace missing values in the 'Cd_x000D_(mg/kg)' column where 'No Amostra' is 14118 with '1,9'
df_metals.loc[df_metals['No Amostra'] == 14199, 'Cd\n(mg/kg)'] = 1.4

In [17]:
# No Amostra = 19587
df_metals[df_metals['No Amostra']==19587]  # CD and Hg wasn´t measured

No Amostra Data de colheita Zona de_x000D_Produção                 Local  \
1894      19587        19/9/2019                    LOB  Frente à Escola Vela   

       Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
1894  Mexilhão         NaN         NaN             0,60   

      Resultados das Determinações de Metais Contaminantes  \
1894                                                NaN      

      Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
1894                     NaN  ...         NaN   NaN              NaN    NaN   

      Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
1894                   NaN          NaN    NaN    NaN   NaN        NaN  

[1 rows x 56 columns]

NOTE: In the Samples 19587, 19588, 19592, 19593 and 19594 Cd and HG wasn´t measured

In [18]:
df_metals[(df_metals['No Amostra']==19587) |
         (df_metals['No Amostra']==19588) |
         (df_metals['No Amostra']==19592) |
         (df_metals['No Amostra']==19593) |
         (df_metals['No Amostra']==19594) ]

No Amostra Data de colheita Zona de_x000D_Produção                 Local  \
1894      19587        19/9/2019                    LOB  Frente à Escola Vela   
1895      19588        19/9/2019                    LOB              Espichel   
1896      19592        24/9/2019                    LOB               Greijau   
1897      19593        24/9/2019                    LOB              Espichel   
1898      19594        24/9/2019                    LOB              Espichel   

               Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
1894          Mexilhão         NaN         NaN             0,60   
1895          Berbigão         NaN         NaN             0,16   
1896     Amêijoa-macha         NaN         NaN           < 0,06   
1897       Amêijoa-boa         NaN         NaN             0,07   
1898  Amêijoa-japonesa         NaN         NaN             0,06   

      Resultados das Determinações de Metais Contaminantes  \
1894                                                NaN      
1895                                                NaN      
1896                                                NaN      
1897                                                NaN      
1898                                                NaN      

      Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
1894                     NaN  ...         NaN   NaN              NaN    NaN   
1895                     NaN  ...         NaN   NaN              NaN    NaN   
1896                     NaN  ...         NaN   NaN              NaN    NaN   
1897                     NaN  ...         NaN   NaN              NaN    NaN   
1898                     NaN  ...         NaN   NaN              NaN    NaN   

      Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
1894                   NaN          NaN    NaN    NaN   NaN        NaN  
1895                   NaN          NaN    NaN    NaN   NaN        NaN  
1896                   NaN          NaN    NaN    NaN   NaN        NaN  
1897                   NaN          NaN    NaN    NaN   NaN        NaN  
1898                   NaN          NaN    NaN    NaN   NaN        NaN  

[5 rows x 56 columns]

_Hg_x000D_(mg/kg)

In [19]:
df_metals[df_metals['Hg\n(mg/kg)'].isnull()]

No Amostra Data de colheita Zona de_x000D_Produção                 Local  \
641       15649       26-07-2016                   ESD1               Setúbal   
1894      19587        19/9/2019                    LOB  Frente à Escola Vela   
1895      19588        19/9/2019                    LOB              Espichel   
1896      19592        24/9/2019                    LOB               Greijau   
1897      19593        24/9/2019                    LOB              Espichel   
1898      19594        24/9/2019                    LOB              Espichel   
1899      19595        24/9/2019                    LOB              Espichel   

               Espécie Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  \
641   Ostra-portuguesa        0,34         NaN             0,16   
1894          Mexilhão         NaN         NaN             0,60   
1895          Berbigão         NaN         NaN             0,16   
1896     Amêijoa-macha         NaN         NaN           < 0,06   
1897       Amêijoa-boa         NaN         NaN             0,07   
1898  Amêijoa-japonesa         NaN         NaN             0,06   
1899        Longueirão         NaN         NaN             0,09   

      Resultados das Determinações de Metais Contaminantes  \
641                                                 NaN      
1894                                                NaN      
1895                                                NaN      
1896                                                NaN      
1897                                                NaN      
1898                                                NaN      
1899                                                NaN      

      Data de_x000D_colheita  ...  24/03/2015  Faro  Ria Formosa ZNV  Geada  \
641                      NaN  ...         NaN   NaN              NaN    NaN   
1894                     NaN  ...         NaN   NaN              NaN    NaN   
1895                     NaN  ...         NaN   NaN              NaN    NaN   
1896                     NaN  ...         NaN   NaN              NaN    NaN   
1897                     NaN  ...         NaN   NaN              NaN    NaN   
1898                     NaN  ...         NaN   NaN              NaN    NaN   
1899                     NaN  ...         NaN   NaN              NaN    NaN   

      Ruditapes decussatus  Amêijoa-boa  0.034  0.021  0.12 Pb (mg/kg)  
641                    NaN          NaN    NaN    NaN   NaN        NaN  
1894                   NaN          NaN    NaN    NaN   NaN        NaN  
1895                   NaN          NaN    NaN    NaN   NaN        NaN  
1896                   NaN          NaN    NaN    NaN   NaN        NaN  
1897                   NaN          NaN    NaN    NaN   NaN        NaN  
1898                   NaN          NaN    NaN    NaN   NaN        NaN  
1899                   NaN          NaN    NaN    NaN   NaN        NaN  

[7 rows x 56 columns]

In [20]:
# Replace missing values in the 'Cd_x000D_(mg/kg)' column where 'No Amostra' is 15649 with '1,9'
df_metals.loc[df_metals['No Amostra']=='15649', 'Hg\n(mg/kg)'] = 0.031

_Remove Columns With More than 15 % of missing values__

In [21]:
# Step 1: Calculate the percentage of missing values in each column
missing_percentage = (df_metals.isnull().sum() / len(df_metals)) * 100

# Step 2: Identify the columns where the percentage of missing values exceeds 15%
columns_to_remove = missing_percentage[missing_percentage > 15].index

# Step 3: Remove those columns from the DataFrame
df_metals.drop(columns=columns_to_remove, inplace=True)

In [22]:
df_metals

No Amostra Data de colheita Zona de_x000D_Produção  \
0        353/21       12/04/2021                    L5a   
1        362/21       13/04/2021                   ETJ1   
2        363/21       13/04/2021                   ESD1   
3        366/21       13/04/2021                RIAV NZ   
4        369/21       19/04/2021                    LOB   
...         ...              ...                    ...   
2156    1046/22       28/09/2022                  RIAV1   
2157    1047/22       28/09/2022                     L1   
2158    1048/22       28/09/2022                     L1   
2159    1049/22       28/09/2022                     L1   
2160    1051/22       28/09/2022                   ESD2   

                               Local           Espécie Cd\n(mg/kg)  \
0                    Praia dos Coxos              Lapa         2.3   
1                           Cacilhas       Pé-de-burro        0.24   
2                      Canal da Vaia  Ostra-portuguesa         0.5   
3                   Bolho da Malhada     Ostra-gigante        0.18   
4                            Greijau   Amêijoa-relógio        0.09   
...                              ...               ...         ...   
2156  Frente Colónia Férias Torreira  Amêijoa-japonesa        0.26   
2157                         Carreço          Mexilhão        0.28   
2158                         Carreço              Lapa         0.8   
2159                         Carreço     Ouriço-do-mar        0.14   
2160                    Carrasqueira        Longueirão        0.07   

     Hg\n(mg/kg) Pb_x000D_(mg/kg)  
0          0.013             0.10  
1          0.028             0.24  
2          0.026             0.12  
3          0.045             0.14  
4          0.011              0.7  
...          ...              ...  
2156       0.017             0.06  
2157       0.012             0.18  
2158     < 0.011             0.37  
2159     < 0.011           < 0.06  
2160       0.020             0.11  

[2159 rows x 8 columns]

__Duplicate Values__

Let´s find duplicate values based on the 'No Amostra'

In [23]:
df_metals[df_metals.duplicated(subset='No Amostra')]

No Amostra Data de colheita Zona de_x000D_Produção    Local      Espécie  \
828     409/22       03/05/2022                   FAR1  Marchil  Amêijoa-boa   

    Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  
828        0.06       0.019             0.16

In [24]:
df_metals[df_metals['No Amostra']=='409/22']

No Amostra Data de colheita Zona de_x000D_Produção     Local      Espécie  \
827     409/22       03/05/2022                   POR2  Povoação  Amêijoa-boa   
828     409/22       03/05/2022                   FAR1   Marchil  Amêijoa-boa   

    Cd\n(mg/kg) Hg\n(mg/kg) Pb_x000D_(mg/kg)  
827        0.05       0.011             0.08  
828        0.06       0.019             0.16

NOTE: The 'No Amostra'=409/22 appers twice, but as we can see from the orinal pdf file this is correct

__Rename Some Columns__

In [25]:
df_metals.rename(columns={'Zona de_x000D_Produção':'Zona de Produção',
                         'Cd\n(mg/kg)':'Cd (mg/kg)',
                         'Hg\n(mg/kg)':'Hg (mg/kg)',
                         'Pb_x000D_(mg/kg)':'Pb (mg/kg)'}, inplace=True)

df_metals

No Amostra Data de colheita Zona de Produção  \
0        353/21       12/04/2021              L5a   
1        362/21       13/04/2021             ETJ1   
2        363/21       13/04/2021             ESD1   
3        366/21       13/04/2021          RIAV NZ   
4        369/21       19/04/2021              LOB   
...         ...              ...              ...   
2156    1046/22       28/09/2022            RIAV1   
2157    1047/22       28/09/2022               L1   
2158    1048/22       28/09/2022               L1   
2159    1049/22       28/09/2022               L1   
2160    1051/22       28/09/2022             ESD2   

                               Local           Espécie Cd (mg/kg) Hg (mg/kg)  \
0                    Praia dos Coxos              Lapa        2.3      0.013   
1                           Cacilhas       Pé-de-burro       0.24      0.028   
2                      Canal da Vaia  Ostra-portuguesa        0.5      0.026   
3                   Bolho da Malhada     Ostra-gigante       0.18      0.045   
4                            Greijau   Amêijoa-relógio       0.09      0.011   
...                              ...               ...        ...        ...   
2156  Frente Colónia Férias Torreira  Amêijoa-japonesa       0.26      0.017   
2157                         Carreço          Mexilhão       0.28      0.012   
2158                         Carreço              Lapa        0.8    < 0.011   
2159                         Carreço     Ouriço-do-mar       0.14    < 0.011   
2160                    Carrasqueira        Longueirão       0.07      0.020   

     Pb (mg/kg)  
0          0.10  
1          0.24  
2          0.12  
3          0.14  
4           0.7  
...         ...  
2156       0.06  
2157       0.18  
2158       0.37  
2159     < 0.06  
2160       0.11  

[2159 rows x 8 columns]

__Missing Values in All Columns At the Same Time__

In [26]:
# Check for missing values in the specified columns
missing_values_mask = df_metals[['Cd (mg/kg)', 'Hg (mg/kg)', 'Pb (mg/kg)']].isnull()

# Check if there are any rows with missing values in all three columns
rows_with_missing_values = missing_values_mask.all(axis=1)

# Filter the dataframe to show only rows with missing values in all three columns
result_df = df_metals[rows_with_missing_values]

result_df

Empty DataFrame
Columns: [No Amostra, Data de colheita, Zona de Produção, Local, Espécie, Cd (mg/kg), Hg (mg/kg), Pb (mg/kg)]
Index: []

__Espécie__

In [27]:
df_metals['Espécie'].value_counts()

Lapa                      263
Mexilhão                  243
Amêijoa-boa               228
Ostra-portuguesa          206
Ostra-japonesa/gigante    183
Amêijoa-japonesa          159
Lambujinha                148
Berbigão                  146
Amêijoa-branca             79
Longueirão                 74
Amêijoa-macha              56
Conquilha                  56
Ostra-gigante              54
Ouriço-do-mar              49
Ostra-plana                31
Castanhola                 31
Ostra-gigante/japonesa     21
Pé-de-burro                17
Amêijola                   14
Canilha                    10
Amêijoa-relógio            10
Crassostrea angulata        9
Ostra                       9
Longueirão-direito          8
Pé-de-burrinho              7
Buzina                      7
Amêijoa-cão                 5
Vieira                      4
Buzinas                     4
Zamburinha                  3
Amêijoa-asiática            3
Scrobicularia plana         3
Leque                       2
Ostra-japo

_Remove Species that aren´t bivalves_
 * Lapa, Ouriço-do-mar, Burrié, Búzio, Buzinas, Canilha, Buzina, Zamburinha 
 * Cerastoderme edule = Berbigão
 * Callista chione = Amêijola
 * Scrobicularia plana = Lambujinha
 * Mytilus edulis = Mexilhão
 * Crassostrea angulata = Ostra-portuguesa
 * Leque = Vieira
 * Navalha = Longueirão
 * Longueirão-direito = Longueirão
 * Catanhola = Amêijola

In [28]:
ñ_bivalve = df_metals[(df_metals['Espécie']=='Lapa') |
         (df_metals['Espécie']=='Ouriço-do-mar') |
         (df_metals['Espécie']=='Burrié') |
         (df_metals['Espécie']=='Búzio') |
         (df_metals['Espécie']=='Buzinas') |
         (df_metals['Espécie']=='Canilha') |
         (df_metals['Espécie']=='Buzina') |
         (df_metals['Espécie']=='Zamburinha')]

df_metals = df_metals.drop(ñ_bivalve.index)

_Mexilhão_

In [29]:
df_metals.loc[df_metals['Espécie'].isin(['Mexihão',
                                            'Mytilus edulis']), 'Espécie'] = 'Mexilhão'

_Amêijoa-boa_

In [30]:
df_metals.loc[df_metals['Espécie'].isin(['Amêija-boa',
                                        'Amêjoa-boa']), 'Espécie'] = 'Amêijoa-boa'

_Berbigão_

In [31]:
df_metals.loc[df_metals['Espécie'].isin(['Cerastoderme edule']),'Espécie'] = 'Berbigão'

_Ostra-portuguesa_

In [32]:
df_metals.loc[df_metals['Espécie'].isin(['Crassostrea angulata']),'Espécie'] = 'Ostra-portuguesa'

_Ostra-japonesa_

In [33]:
df_metals.loc[df_metals['Espécie'].isin(['Ostra-japonesa/gigante',
                                          'Ostra-gigante',
                                          'Ostra-japonesa',
                                          'Ostra-gigante/japonesa']),'Espécie'] = 'Ostra-japonesa'

_Amêijoa-japonesa_

In [34]:
df_metals.loc[df_metals['Espécie'].isin(['Amêijoa-asiática',
                                        'Amêija-japonesa']),'Espécie'] = 'Amêijoa-japonesa'

_Vieira_

In [35]:
df_metals.loc[df_metals['Espécie'].isin(['Leque']),'Espécie'] = 'Vieira'

_Longueirão_

In [36]:
df_metals.loc[df_metals['Espécie'].isin(['Navalha',
                                        'Longueirão-direito']), 'Espécie'] = 'Longueirão'

_Amêijola_

In [37]:
df_metals.loc[df_metals['Espécie'].isin(['Callista chione',
                                        'Castanhola']),'Espécie'] = 'Amêijola'

_Lambujinha_

In [38]:
df_metals.loc[df_metals['Espécie'].isin(['Scrobicularia plana']),'Espécie'] = 'Lambujinha'

_Pé-de-burro_

In [39]:
df_metals.loc[df_metals['Espécie'].isin(['Pé-de burrinho',
                                        'Pé-de-burrico',
                                        'Pé-de-burrinho']),'Espécie'] = 'Pé-de-burro'

__Deal With LD Values__

In [40]:
df_metals.head()

No Amostra Data de colheita Zona de Produção             Local  \
1     362/21       13/04/2021             ETJ1          Cacilhas   
2     363/21       13/04/2021             ESD1     Canal da Vaia   
3     366/21       13/04/2021          RIAV NZ  Bolho da Malhada   
4     369/21       19/04/2021              LOB           Greijau   
5     376/21       20/04/2021             L7c2      Offshore MS1   

            Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
1       Pé-de-burro       0.24      0.028       0.24  
2  Ostra-portuguesa        0.5      0.026       0.12  
3    Ostra-japonesa       0.18      0.045       0.14  
4   Amêijoa-relógio       0.09      0.011        0.7  
5       Amêijoa-boa       0.06    < 0,011       0.02

In [41]:
# Cd (mg/kg)
df_metals['Cd (mg/kg)'].value_counts()

0,05     74
0,06     54
0,07     51
0,11     48
0,08     44
         ..
0,44      1
0,018     1
2         1
0.56      1
0.26      1
Name: Cd (mg/kg), Length: 244, dtype: int64

In [42]:
df_metals[df_metals['Cd (mg/kg)']=='LD']

Empty DataFrame
Columns: [No Amostra, Data de colheita, Zona de Produção, Local, Espécie, Cd (mg/kg), Hg (mg/kg), Pb (mg/kg)]
Index: []

In [43]:
# Hg (mg/kg)
df_metals['Hg (mg/kg)'].value_counts()

< 0,011    202
0,016       53
0,014       50
0,011       49
< 0.011     48
          ... 
0.039        1
0,6          1
0,090        1
0,052        1
0.044        1
Name: Hg (mg/kg), Length: 181, dtype: int64

In [44]:
df_metals[df_metals['Hg (mg/kg)']=='LD']

Empty DataFrame
Columns: [No Amostra, Data de colheita, Zona de Produção, Local, Espécie, Cd (mg/kg), Hg (mg/kg), Pb (mg/kg)]
Index: []

In [45]:
# Pb (mg/kg)
ld_pb = df_metals[df_metals['Pb (mg/kg)']=='LD']
ld_pb

No Amostra Data de colheita Zona de Produção      Local  \
1568     942/21       13/10/2021             OLH4   Garganta   
1576     981/21       21/10/2021              EMR  Roncanito   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
1568       Amêijoa-boa       0.05      0.027         LD  
1576  Ostra-portuguesa        0.5         LQ         LD

In [46]:
# Drop values with 'LD'
df_metals.drop(ld_pb.index,inplace=True)

__Deal With LQ Values__

Let´s replace the values with "<" or with LQ by one value above the lowest found

In [47]:
# Cd (mg/kg)
df_metals[(df_metals['Cd (mg/kg)'].str.contains('<')) | 
           (df_metals['Cd (mg/kg)'].str.contains('LQ'))]

Empty DataFrame
Columns: [No Amostra, Data de colheita, Zona de Produção, Local, Espécie, Cd (mg/kg), Hg (mg/kg), Pb (mg/kg)]
Index: []

In [48]:
# Hg (mg/kg)
hg_lq = df_metals[(df_metals['Hg (mg/kg)'].str.contains('<')) | 
           (df_metals['Hg (mg/kg)'].str.contains('LQ'))]

hg_lq

No Amostra Data de colheita Zona de Produção                    Local  \
5        376/21       20/04/2021             L7c2             Offshore MS1   
28      1169/21       06/12/2021              LOB                  Greijau   
29      1171/21       06/12/2021              LOB    Frente Escola de Vela   
32      1215/21       15/12/2021              EMR                Roncanito   
35        60/22       08/02/2022              EMR                Roncanito   
...         ...              ...              ...                      ...   
2145    1023/22       27/09/2022              EMR                Roncanito   
2146    1024/22       27/09/2022               L2         Leça da Palmeira   
2148    1038/22       28/09/2022              ELM  Montante Ponte Eiffel 1   
2149    1039/22       28/09/2022              ELM  Montante Ponte Eiffel 1   
2155    1045/22       28/09/2022            RIAV1  Entrada da Cale do Ouro   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
5          Amêijoa-boa       0.06    < 0,011       0.02  
28       Amêijoa-macha       0.06    < 0,011     < 0,02  
29            Mexilhão      0.036    < 0,011       0,02  
32    Ostra-portuguesa        0.9    < 0,011     < 0,02  
35    Ostra-portuguesa        1,2    < 0,011     < 0,06  
...                ...        ...        ...        ...  
2145  Ostra-portuguesa        1.4    < 0.011     < 0.06  
2146          Mexilhão       0.25    < 0.011       0.14  
2148    Ostra-japonesa       0.20    < 0.011       0.10  
2149  Ostra-portuguesa       0.31    < 0.011       0.13  
2155          Berbigão       0.16    < 0.011       0.10  

[261 rows x 8 columns]

In [49]:
hg_lq['Hg (mg/kg)'].value_counts()

< 0,011    202
< 0.011     48
< 0,010      6
< 0,004      3
LQ           1
< 0,06       1
Name: Hg (mg/kg), dtype: int64

In [50]:
# Let´s replace the values with < or LQ in the 'Hg (mg/kg)' column by 0,003
df_metals.loc[hg_lq.index, 'Hg (mg/kg)'] = 0.03

In [51]:
df_metals[df_metals['Hg (mg/kg)']==0.03]

No Amostra Data de colheita Zona de Produção                    Local  \
5        376/21       20/04/2021             L7c2             Offshore MS1   
28      1169/21       06/12/2021              LOB                  Greijau   
29      1171/21       06/12/2021              LOB    Frente Escola de Vela   
32      1215/21       15/12/2021              EMR                Roncanito   
35        60/22       08/02/2022              EMR                Roncanito   
...         ...              ...              ...                      ...   
2145    1023/22       27/09/2022              EMR                Roncanito   
2146    1024/22       27/09/2022               L2         Leça da Palmeira   
2148    1038/22       28/09/2022              ELM  Montante Ponte Eiffel 1   
2149    1039/22       28/09/2022              ELM  Montante Ponte Eiffel 1   
2155    1045/22       28/09/2022            RIAV1  Entrada da Cale do Ouro   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
5          Amêijoa-boa       0.06       0.03       0.02  
28       Amêijoa-macha       0.06       0.03     < 0,02  
29            Mexilhão      0.036       0.03       0,02  
32    Ostra-portuguesa        0.9       0.03     < 0,02  
35    Ostra-portuguesa        1,2       0.03     < 0,06  
...                ...        ...        ...        ...  
2145  Ostra-portuguesa        1.4       0.03     < 0.06  
2146          Mexilhão       0.25       0.03       0.14  
2148    Ostra-japonesa       0.20       0.03       0.10  
2149  Ostra-portuguesa       0.31       0.03       0.13  
2155          Berbigão       0.16       0.03       0.10  

[265 rows x 8 columns]

In [52]:
# Pb (mg/kg)
pb_lq = df_metals[(df_metals['Pb (mg/kg)'].str.contains('<')) |
         (df_metals['Pb (mg/kg)'].str.contains('LQ'))]

pb_lq

No Amostra Data de colheita Zona de Produção                Local  \
6        377/21       20/04/2021             L7c2         Offshore MS1   
11       630/20      17-ago-2020          RIAV NZ     Bolho da Malhada   
17       662/20      31-ago-2020              LAL              Jangada   
27      1168/21       06/12/2021              LOB             Espichel   
28      1169/21       06/12/2021              LOB              Greijau   
...         ...              ...              ...                  ...   
2105     946/22       13/09/2022              LOB              Greijau   
2133     999/22       20/09/2022            RIAV2       Ponte da Barra   
2134    1000/22       20/09/2022            RIAV1               Moacha   
2135    1003/22       21/09/2022            RIAV4  Sul da Ponte da A25   
2145    1023/22       27/09/2022              EMR            Roncanito   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
6        Amêijoa-macha       0.15      0.017     < 0,06  
11      Ostra-japonesa       0,07      0,027     < 0,06  
17            Mexilhão       0,09      0,025     < 0,06  
27    Amêijoa-japonesa      0.036      0.016     < 0,06  
28       Amêijoa-macha       0.06       0.03     < 0,02  
...                ...        ...        ...        ...  
2105     Amêijoa-macha       0.12       0.03     < 0.06  
2133     Amêijoa-macha       0.31      0.012     < 0.06  
2134     Amêijoa-macha       0.29      0.013     < 0.06  
2135     Amêijoa-macha       0.16      0.012     < 0.06  
2145  Ostra-portuguesa        1.4       0.03     < 0.06  

[177 rows x 8 columns]

In [53]:
pb_lq['Pb (mg/kg)'].value_counts()

< 0,06     136
< 0.06      31
< 0,02       7
LQ           2
< 0,011      1
Name: Pb (mg/kg), dtype: int64

In [54]:
# Let´s replace every values with '<' or 'LQ' by 0.01
df_metals.loc[pb_lq.index, 'Pb (mg/kg)'] = 0.01

In [55]:
df_metals[df_metals['Pb (mg/kg)']==0.01]

No Amostra Data de colheita Zona de Produção                Local  \
6        377/21       20/04/2021             L7c2         Offshore MS1   
11       630/20      17-ago-2020          RIAV NZ     Bolho da Malhada   
17       662/20      31-ago-2020              LAL              Jangada   
27      1168/21       06/12/2021              LOB             Espichel   
28      1169/21       06/12/2021              LOB              Greijau   
...         ...              ...              ...                  ...   
2105     946/22       13/09/2022              LOB              Greijau   
2133     999/22       20/09/2022            RIAV2       Ponte da Barra   
2134    1000/22       20/09/2022            RIAV1               Moacha   
2135    1003/22       21/09/2022            RIAV4  Sul da Ponte da A25   
2145    1023/22       27/09/2022              EMR            Roncanito   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
6        Amêijoa-macha       0.15      0.017       0.01  
11      Ostra-japonesa       0,07      0,027       0.01  
17            Mexilhão       0,09      0,025       0.01  
27    Amêijoa-japonesa      0.036      0.016       0.01  
28       Amêijoa-macha       0.06       0.03       0.01  
...                ...        ...        ...        ...  
2105     Amêijoa-macha       0.12       0.03       0.01  
2133     Amêijoa-macha       0.31      0.012       0.01  
2134     Amêijoa-macha       0.29      0.013       0.01  
2135     Amêijoa-macha       0.16      0.012       0.01  
2145  Ostra-portuguesa        1.4       0.03       0.01  

[177 rows x 8 columns]

__Zonas de Produção__

In [56]:
count_zonas = df_metals['Zona de Produção'].value_counts()
count_zonas

ETJ      158
LOB      120
ESD1      97
EMR       95
ESD2      66
        ... 
Fuz        1
FAR 1      1
LAG1       1
OLH6       1
ZT         1
Name: Zona de Produção, Length: 80, dtype: int64

In [57]:
# Zonas de Produção with less then 20 value counts
count_zonas[count_zonas < 20]

OLH3                                              18
EMN2                                              15
L5a                                               13
TAV2                                              12
L7a                                               12
L5                                                12
GUA                                               12
FUZ1                                              11
L7c1                                              11
ETJ2                                              11
POR3                                               9
VT                                                 8
Estuário do Sado                                   8
EMN                                                8
L7B                                                7
L7b                                                7
Estuário do Mira                                   4
EMN2 Braço Sul                                     4
L7c                                           

In [58]:
df_metals[df_metals['Zona de Produção'].str.contains('Estuário')]

No Amostra Data de colheita          Zona de Produção  \
415       13041        6/10/2014          Estuário do Tejo   
416       13140       22/10/2014          Estuário do Sado   
418       13166       29/10/2014          Estuário do Mira   
419       13188        5/11/2014          Estuário do Sado   
420       13189        5/11/2014          Estuário do Sado   
421       13204       10/11/2014          Estuário do Tejo   
422       13214       10/11/2014       Estuário do Mondego   
423       13281       25/11/2014          Estuário do Mira   
425       13330        3/12/2014          Estuário do Sado   
426       13341        9/12/2014          Estuário do Tejo   
428       14785        9/12/2015          Estuário do Tejo   
429       14825       10/12/2015          Estuário do Mira   
430       14868       15/12/2015          Estuário do Sado   
431       14886       16/12/2015          Estuário do Sado   
746       15388       18-05-2016    Estuário do Sado -ESD1   
747       15398       19-05-2016  Estuário do Mondego EMN2   
748       15435       30-05-2016     Estuário do Mira -EMR   
749       15436       30-05-2016     Estuário do Mira -EMR   
1362      14633       11/11/2015          Estuário do Sado   
1363      14642       12/11/2015          Estuário do Sado   
1364      14645       16/11/2015          Estuário do Mira   

                    Local           Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
415               Samouco        Lambujinha       0.04      0.038        2.2  
416                  Abul  Ostra-portuguesa        1.1      0.005       0.09  
418           Casa Branca  Ostra-portuguesa        0.6      0.011       0.28  
419         Canal da Vaia  Ostra-portuguesa        0.4      0.012       0.36  
420                  Abul  Ostra-portuguesa        0.9      0.005       0.34  
421               Samouco        Lambujinha       0.04      0.046        1.4  
422      Murraceira Norte          Berbigão      0.035      0.012       0.47  
423           Casa Branca  Ostra-portuguesa        1.1      0.017       0.06  
425         Canal da Vaia  Ostra-portuguesa        0.5       0.02       0.12  
426               Samouco        Lambujinha       0.06      0.048          3  
428         Paço de Arcos       Pé-de-burro       0.16      0.014       0.17  
429    Roncão/Casa Branca  Ostra-portuguesa        1.1      0.016       0.01  
430   Casas Novas/Batalha  Ostra-portuguesa        1.9      0.022       0.13  
431         Canal da Vaia  Ostra-portuguesa        0.5      0.026       0.11  
746         Canal da Vaia  Ostra-portuguesa        0,6      0,027       0,16  
747        Murraceira Sul        Lambujinha       0,08      0,029        1,2  
748           Casa Branca  Ostra-portuguesa        0,4      0,010       0,14  
749                Roncão  Ostra-portuguesa        0,4      0,010       0,08  
1362        Canal da Vaia  Ostra-portuguesa        0.8       0.03       0.11  
1363  Casas Novas/Batalha  Ostra-portuguesa        1.4      0.015       0.16  
1364   Roncão/Casa Branca  Ostra-portuguesa        1.1       0.02       0.07

_ETJ_

In [59]:
df_metals[df_metals['Zona de Produção'].str.contains('ETJ')]['Zona de Produção'].value_counts()

ETJ     158
ETJ1     41
ETJ2     11
Name: Zona de Produção, dtype: int64

In [60]:
df_metals.loc[df_metals['Zona de Produção'].isin(['ETJ1',
                                                  'ETJ2',
                                                 'Estuário do Tejo']), 'Zona de Produção'] = 'ETJ'


_LOB_

In [61]:
df_metals[df_metals['Zona de Produção'].str.contains('LOB')]['Zona de Produção'].value_counts()

LOB    120
Name: Zona de Produção, dtype: int64

_ESD_

In [62]:
df_metals[df_metals['Zona de Produção'].str.contains('ESD')]['Zona de Produção'].value_counts()

ESD1                          97
ESD2                          66
ESD1 Esteiro da Marateca      21
ESD2 Canal de Alcácer         21
ESD1 - Esteiro da Marateca     1
Estuário do Sado -ESD1         1
Name: Zona de Produção, dtype: int64

In [63]:
# ESD1
df_metals.loc[df_metals['Zona de Produção'].isin(['ESD1 Esteiro da Marateca',
                                                'ESD1 - Esteiro da Marateca',
                                                'Estuário do Sado -ESD1',
                                                 'Estuário do Sado']),'Zona de Produção'] = 'ESD1'

In [64]:
# ESD2
df_metals.loc[df_metals['Zona de Produção'].isin(['ESD2 Canal de Alcácer']),'Zona de Produção'] = 'ESD2'

_EMN_

In [65]:
df_metals[df_metals['Zona de Produção'].str.contains('EMN')] ['Zona de Produção'].value_counts()

EMN2                        15
EMN                          8
EMN ZN                       4
EMN NZ                       4
EMN2 Braço Sul               4
EMN1                         4
EMN1 Braço Norte             2
EMN2 - Braço Sul             1
Estuário do Mondego EMN2     1
Name: Zona de Produção, dtype: int64

In [66]:
# EMN 
df_metals.loc[df_metals['Zona de Produção'].isin(['EMN2',
                                                 'EMN ZN',
                                                 'EMN NZ',
                                                 'EMN2 Braço Sul',
                                                 'EMN1',
                                                 'EMN1 Braço Norte',
                                                  'EMN2 - Braço Sul',
                                                 'Estuário do Mondego EMN2',
                                                 'Estuário do Mondego']), 'Zona de Produção'] = 'EMN'

_EMR_

In [67]:
df_metals[df_metals['Zona de Produção'].str.contains('EMR')]['Zona de Produção'].value_counts()

EMR                      95
Estuário do Mira -EMR     2
Name: Zona de Produção, dtype: int64

In [68]:
df_metals.loc[df_metals['Zona de Produção'].isin(['Estuário do Mira -EMR',
                                                 'Estuário do Mira']), 'Zona de Produção'] = 'EMR'

_L_
* Litoral

In [69]:
df_metals[df_metals['Zona de Produção'].str.contains('L')]['Zona de Produção'].value_counts()

LOB                                      120
L6                                        52
L2                                        51
OLH2                                      47
OLH5                                      41
LAG                                       39
OLH4                                      38
L8                                        36
L7c2                                      36
ELM                                       35
L3                                        32
OLH1                                      29
L1                                        27
L5b                                       27
L4                                        24
L9                                        22
LAL                                       20
OLH3                                      18
L5a                                       13
L5                                        12
L7a                                       12
L7c1                                      11
L7b       

In [70]:
# L1 ---- Litoral Viana
df_metals[df_metals['Zona de Produção'].str.contains('L1')]['Zona de Produção'].value_counts()

L1    27
Name: Zona de Produção, dtype: int64

In [71]:
# L2 -- Litoral Matosinhos
df_metals[df_metals['Zona de Produção'].str.contains('L2')]['Zona de Produção'].value_counts()

L2    51
Name: Zona de Produção, dtype: int64

In [72]:
# L3 --- Litoral Aveiro
df_metals[df_metals['Zona de Produção'].str.contains('L3')]['Zona de Produção'].value_counts()

L3    32
Name: Zona de Produção, dtype: int64

In [73]:
# L4 --- Litoral Figueira da Foz - Nazaré
df_metals[df_metals['Zona de Produção'].str.contains('L4')]['Zona de Produção'].value_counts()

L4    24
Name: Zona de Produção, dtype: int64

In [74]:
df_metals[df_metals['Zona de Produção'].str.contains('Figueira')]['Zona de Produção'].value_counts()

Litoral Figueira da Foz-_x000D_Nazaré    1
Name: Zona de Produção, dtype: int64

In [75]:
df_metals.loc[df_metals['Zona de Produção'].isin(['Litoral Figueira da Foz-_x000D_Nazaré']),'Zona de Produção'] = 'L4'

In [76]:
# L5a, L5b 
df_metals[df_metals['Zona de Produção'].str.contains('L5')]['Zona de Produção'].value_counts()

L5b    27
L5a    13
L5     12
Name: Zona de Produção, dtype: int64

In [77]:
df_metals.loc[df_metals['Zona de Produção'].isin(['L5b',
                                                 'L5a']),'Zona de Produção'] = 'L5'

In [78]:
# L6 --- Litoral Setubal-Sines
df_metals[df_metals['Zona de Produção'].str.contains('L6')]['Zona de Produção'].value_counts()

L6    52
Name: Zona de Produção, dtype: int64

In [79]:
df_metals.loc[df_metals['Zona de Produção'].isin(['Litoral Sines-Setúbal']),'Zona de Produção'] = 'L6'

In [80]:
# L7
df_metals[df_metals['Zona de Produção'].str.contains('L7')]['Zona de Produção'].value_counts()

L7c2    36
L7a     12
L7c1    11
L7b      7
L7B      7
L7c      4
L7C      4
L7A      3
Name: Zona de Produção, dtype: int64

In [81]:
df_metals.loc[df_metals['Zona de Produção'].isin(['L7A']),'Zona de Produção'] = 'L7a'

In [82]:
df_metals.loc[df_metals['Zona de Produção'].isin(['L7B']),'Zona de Produção'] = 'L7b'

In [83]:
df_metals.loc[df_metals['Zona de Produção'].isin(['L7C','L7c']),'Zona de Produção'] = 'L7c1'

In [84]:
# Litoral Sines-Setúbal
df_metals[df_metals['Zona de Produção']=='Litoral Sines-Setúbal']

Empty DataFrame
Columns: [No Amostra, Data de colheita, Zona de Produção, Local, Espécie, Cd (mg/kg), Hg (mg/kg), Pb (mg/kg)]
Index: []

_RIAV_

In [85]:
df_metals[df_metals['Zona de Produção'].str.contains('RIAV')]['Zona de Produção'].value_counts()

RIAV3      65
RIAV4      62
RIAV2      61
RIAV1      60
RIAV NZ     3
Name: Zona de Produção, dtype: int64

In [86]:
# RIAV NZ doesn´t exist so let´s examine it
df_metals[df_metals['Zona de Produção']=='RIAV NZ']

No Amostra Data de colheita Zona de Produção             Local  \
3        366/21       13/04/2021          RIAV NZ  Bolho da Malhada   
11       630/20      17-ago-2020          RIAV NZ  Bolho da Malhada   
2074     891/21       28/09/2021          RIAV NZ  Bolho da Malhada   

             Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
3     Ostra-japonesa       0.18      0.045       0.14  
11    Ostra-japonesa       0,07      0,027       0.01  
2074  Ostra-japonesa       0.36      0.036       0.09

In [87]:
# RIAV NZ is the Same as RIAV 4
df_metals['Zona de Produção'] = df_metals['Zona de Produção'].str.replace('RIAV NZ','RIAV4')

In [88]:
df_metals[df_metals['Zona de Produção'].str.contains('Aveiro')]

No Amostra Data de colheita  \
417      13156       27/10/2014   

                                   Zona de Produção       Local   Espécie  \
417  Ria de Aveiro/Canal_x000D_Principal-Espinheiro  Espinheiro  Berbigão   

    Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
417       0.05      0.019       0.41

In [89]:
df_metals.loc[df_metals['Zona de Produção'].isin(['Ria de Aveiro/Canal_x000D_Principal-Espinheiro']),'Zona de Produção'] = 'RIAV3'

_OLH_

In [90]:
df_metals[df_metals['Zona de Produção'].str.contains('OLH')]['Zona de Produção'].value_counts()

OLH2    47
OLH5    41
OLH4    38
OLH1    29
OLH3    18
OLH6     1
Name: Zona de Produção, dtype: int64

In [91]:
# OLH6 doesn´t exist therefore let´s remove it
olh6 = df_metals[df_metals['Zona de Produção']=='OLH6']
olh6

No Amostra Data de colheita Zona de Produção    Local         Espécie  \
1729      17075          6/09/17             OLH6  Culatra  Ostra-japonesa   

     Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
1729       0.15      0.027       0.19

In [92]:
df_metals.drop(olh6.index,inplace=True)

_FAR_

In [93]:
df_metals[df_metals['Zona de Produção'].str.contains('FAR')]['Zona de Produção'].value_counts()

FAR2     37
FAR1     32
FAR 2     3
FAR 1     1
Name: Zona de Produção, dtype: int64

In [94]:
# FAR1
df_metals.loc[df_metals['Zona de Produção'].isin(['FAR 1']),'Zona de Produção'] = 'FAR1'

In [95]:
# FAR2
df_metals.loc[df_metals['Zona de Produção'].isin(['FAR 2']),'Zona de Produção'] = 'FAR2'

_POR_

In [96]:
df_metals[df_metals['Zona de Produção'].str.contains('POR')]['Zona de Produção'].value_counts()

POR2     29
POR3      9
POR 2     2
Name: Zona de Produção, dtype: int64

In [97]:
# POR2
df_metals.loc[df_metals['Zona de Produção'].isin(['POR 2']),'Zona de Produção'] = 'POR2' 

_VT_

In [98]:
df_metals[df_metals['Zona de Produção'].str.contains('VT')]['Zona de Produção'].value_counts()

VT      8
VT 1    4
VT1     2
Name: Zona de Produção, dtype: int64

In [99]:
df_metals.loc[df_metals['Zona de Produção'].isin(['VT 1',
                                                 'VT1']),'Zona de Produção'] = 'VT'

_LAG_

In [100]:
df_metals[df_metals['Zona de Produção'].str.contains('LAG')]['Zona de Produção'].value_counts()

LAG     39
LAG1     1
Name: Zona de Produção, dtype: int64

In [101]:
df_metals.loc[df_metals['Zona de Produção'].isin(['LAG1']),'Zona de Produção'] = 'LAG'

_ZT_

In [102]:
df_metals[df_metals['Zona de Produção'].str.contains('ZT')]

No Amostra Data de colheita Zona de Produção               Local  \
1779      18338         4/9/2018               ZT  Cabo de S. Vicente   

          Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
1779  Amêijoa-boa       0,15      0,021       0,06

In [103]:
# There is no 'ZT' therefore let´s drop it
zt = df_metals[df_metals['Zona de Produção']=='ZT']
zt

No Amostra Data de colheita Zona de Produção               Local  \
1779      18338         4/9/2018               ZT  Cabo de S. Vicente   

          Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
1779  Amêijoa-boa       0,15      0,021       0,06

In [104]:
df_metals.drop(zt.index,inplace=True)

_FUZ_

In [105]:
df_metals[df_metals['Zona de Produção'].str.contains('FUZ')]['Zona de Produção'].value_counts()

FUZ     27
FUZ1    11
Name: Zona de Produção, dtype: int64

In [106]:
df_metals['Zona de Produção'] = df_metals['Zona de Produção'].str.replace('FUZ1','FUZ')

In [107]:
df_metals[df_metals['Zona de Produção'].str.contains('Fuz')]['Zona de Produção'].value_counts()

Fuz    1
Name: Zona de Produção, dtype: int64

In [108]:
df_metals['Zona de Produção'] = df_metals['Zona de Produção'].str.replace('Fuz','FUZ')

_EMI_

In [109]:
emi = df_metals[df_metals['Zona de Produção'].str.contains('EMI')]
emi

No Amostra Data de colheita Zona de Produção                  Local  \
240       15227      06-Abr-2016              EMI  Vila Nova de Cerveira   
1638      14313       14/09/2015              EMI  Vila Nova de Cerveira   
1683      15829       6-Set-2016              EMI  Vila Nova de Cerveira   

               Espécie Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
240   Amêijoa-japonesa       0,18      0,024       0,20  
1638  Amêijoa-japonesa       0.17      0.026       0.02  
1683  Amêijoa-japonesa       0,05      0,021       0,11

_ZNV_

In [110]:
znv = df_metals[df_metals['Zona de Produção'].str.contains('ZNV')]
znv

No Amostra Data de colheita Zona de Produção     Local      Espécie  \
851       13556       11/03/2015              ZNV   Deserta  Amêijoa-boa   
852       13557       11/03/2015              ZNV  Barrinha  Amêijoa-boa   
867       13593       23/03/2015              ZNV     Olhão  Amêijoa-boa   
1716      15903      28-Set-2016              ZNV   Deserta  Amêijoa-boa   

     Cd (mg/kg) Hg (mg/kg) Pb (mg/kg)  
851        0.04      0.023       0.15  
852        0.04      0.023       0.14  
867       0.037      0.022       0.11  
1716       0,05      0,024       0.01

_TAV_

In [111]:
df_metals[df_metals['Zona de Produção'].str.contains('TAV')]['Zona de Produção'].value_counts()

TAV     24
TAV2    12
Name: Zona de Produção, dtype: int64

In [112]:
df_metals['Zona de Produção'] = df_metals['Zona de Produção'].str.replace('TAV2','TAV')

In [113]:
df_metals.drop(columns=['Local'],inplace=True)

In [114]:
df_metals.to_excel('C:/Users/Administrador/Article/DATA_CLEAN/heavy_metals.xlsx',index=False)

In [115]:
df_metals['Espécie'].value_counts()

Ostra-japonesa      259
Mexilhão            245
Amêijoa-boa         227
Ostra-portuguesa    214
Amêijoa-japonesa    163
Lambujinha          151
Berbigão            148
Longueirão           83
Amêijoa-branca       79
Amêijoa-macha        56
Conquilha            56
Amêijola             46
Ostra-plana          31
Pé-de-burro          27
Amêijoa-relógio      10
Ostra                 9
Vieira                6
Amêijoa-cão           5
Taralhão              2
Name: Espécie, dtype: int64